var placeDetails=[
    {key:1,place:"Cox's Bazar",description:"Cox’s Bazar is a town on the southeast coast of Bangladesh. It’s known for its very long, sandy beachfront, stretching from Sea Beach in the north to Kolatoli Beach in the south. Aggameda Khyang monastery is home to bronze statues and centuries-old Buddhist manuscripts. South of town, the tropical rainforest of Himchari National Park has waterfalls and many birds. North, sea turtles breed on nearby Sonadia Island.",image:"https://i.ibb.co/f2ZWCMN/Coxs.png",cardImage:"https://i.ibb.co/KFkHxgD/Coxs.png",lat:21.4272,lng:92.0058},
    {key:2,place:"Sajek",description:"Cox’s Bazar is a town on the southeast coast of Bangladesh. It’s known for its very long, sandy beachfront, stretching from Sea Beach in the north to Kolatoli Beach in the south. Aggameda Khyang monastery is home to bronze statues and centuries-old Buddhist manuscripts. South of town, the tropical rainforest of Himchari National Park has waterfalls and many birds. North, sea turtles breed on nearby Sonadia Island.",image:"https://i.ibb.co/Fb5QW5H/Sajek.png",cardImage:"https://i.ibb.co/SnksvgS/Sajek.png",lat:23.3820,lng:92.2938},
    {key:3,place:"Sreemongol",description:"Cox’s Bazar is a town on the southeast coast of Bangladesh. It’s known for its very long, sandy beachfront, stretching from Sea Beach in the north to Kolatoli Beach in the south. Aggameda Khyang monastery is home to bronze statues and centuries-old Buddhist manuscripts. South of town, the tropical rainforest of Himchari National Park has waterfalls and many birds. North, sea turtles breed on nearby Sonadia Island.",image:"https://i.ibb.co/gTk0MHy/Sreemongol.png",cardImage:"https://i.ibb.co/vYLR5y0/Sreemongol.png",lat:24.3065,lng:91.7296},
    {key:4,place:"Sundorbon",description:"Cox’s Bazar is a town on the southeast coast of Bangladesh. It’s known for its very long, sandy beachfront, stretching from Sea Beach in the north to Kolatoli Beach in the south. Aggameda Khyang monastery is home to bronze statues and centuries-old Buddhist manuscripts. South of town, the tropical rainforest of Himchari National Park has waterfalls and many birds. North, sea turtles breed on nearby Sonadia Island.",
    image:"https://i.ibb.co/7CfptRP/sundorbon.png",cardImage:"https://i.ibb.co/QKmLdZb/sundorbon.png",lat:22.0627,lng:88.0833}

]

export default placeDetails;

